spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.20.250.21:32252/monitor?createDatabaseIfNotExist=true&characterEncoding=utf-8
    username: root
    password: 369369
kubernetes:
  admin-conf: classpath:k8s/admin-local.conf

# 普罗米修细http请求
prometheus:
  queryRange:
    url: http://10.20.250.21:30003/api/v1/query_range
  query:
    url: http://10.20.250.21:30003/api/v1/query
  alert:
    reloadUrl: http://10.20.250.21:30003/-/reload

approval:
  login_url: http://ll.242.211:9090
  approval_url: http://ll.242.211:9090
  username: linjb
  md5Password: e10adc3949ba59abbe56e057f20f883e