spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://*.16.21.180:3306/monitor2?createDatabaseIfNotExist=true&characterEncoding=utf-8
    username: fdp
    password: fdp!@#
kubernetes:
  admin-conf: classpath:k8s/admin-dev.conf

# 普罗米修细http请求
prometheus:
  queryRange:
    url: http://10.20.250.21:30003/api/v1/query_range
  query:
    url: http://10.20.250.21:30003/api/v1/query
  alert:
    reloadUrl: http://10.20.250.21:30003/-/reload

approval:
  login_url: http://*.16.1.223:8981
  approval_url: http://*.16.1.223:8981
  username: linjb
  md5Password: e10adc3949ba59abbe56e057f20f883e