#开发环境配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://*.16.21.180:3306/ecs?createDatabaseIfNotExist=true&characterEncoding=utf-8
    username: fdp
    password: fdp!@#
  rabbitmq:
    addresses: *.16.21.189
    username: admin
    password: admin
    port: 5672
kubernetes:
  admin-conf: classpath:k8s/admin-dev.conf

# 工作中心审核地址
approval:
  gateway: http://*.16.1.223:8981
