#测试环境配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.20.250.63:3306/ecs?createDatabaseIfNotExist=true&characterEncoding=utf-8
    username: ll
    password: ll!@#
  rabbitmq:
    addresses: 10.20.250.62
    username: admin
    password: admin123
    port: 5672
kubernetes:
  admin-conf: classpath:k8s/admin-beta.conf

# 工作中心审核地址
approval:
  gateway: http://10.20.250.61:8981
