spring:
  application:
    name: app-manage
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.31.2.240:3306/ama?createDatabaseIfNotExist=true&characterEncoding=utf-8
    username: fdp
    password: Fdp123!@#
  rabbitmq:
    addresses: 47.105.191.240
    username: admin
    password: fx0202Admin^
    port: 5672
kubernetes:
  admin-conf: classpath:k8s/admin-prod2.conf
docker-java:
  dockerHost: tcp://172.31.2.236:2375
  registerUrl: 172.31.2.236/library
  username: admin
  password: Admin@harbor2019
elasticsearch:
  name: kubernetes-logging
  ips: 172.31.2.236,172.31.2.237,172.31.2.239
  user: elastic
  password: UKyYEzxrYq5zP9LGfuU7
  port: 9400
  index: k8s*

# 工作中心审核地址
approval:
  gateway: http://47.104.242.211:9090

minio:
  url: http://172.16.12.22:9000
  accessKey: minioadmin
  secretKey: minioadmin
